/* 2018.11.16 Create Script for LBMDS Postgresql  */
-- 워크넷_구인_목록
CREATE TABLE SRV_DT_WORKNET_MASTER (
	JO_AUTH_NO        CHARACTER VARYING(20)  NOT NULL, -- 구인인증번호
	CORP_NM           CHARACTER VARYING(100) NOT NULL, -- 회사명
	BSNM_NO           CHAR(13)      NOT NULL, -- 사업자번호
	RECRU_TITLE       CHARACTER VARYING(200) NOT NULL, -- 채용제목
	WAGE_TYPE_RAW     CHARACTER VARYING(20)  NULL,     -- 임금형태원시
	SALARY_RAW        CHARACTER VARYING(50)  NOT NULL, -- 급여원시
	WORK_REGION       CHARACTER VARYING(200) NULL,     -- 근무지역
	WORK_TYPE_RAW     CHARACTER VARYING(50)  NOT NULL, -- 근무형태원시
	MIN_ACDMCR        CHARACTER VARYING(20)  NULL,     -- 최소학력
	MAX_ACDMCR        CHARACTER VARYING(20)  NULL,     -- 최대학력
	CAREER_RAW        CHARACTER VARYING(100) NOT NULL, -- 경력원시
	REG_DT_RAW        CHARACTER VARYING(10)  NOT NULL, -- 등록일자원시
	CLOS_DT_RAW       CHARACTER VARYING(50)  NOT NULL, -- 마감일자원시
	INFO_PROVD_OFFIC  CHARACTER VARYING(50)  NULL,     -- 정보제공처
	RECRU_ROBOT_URL   CHARACTER VARYING(500) NULL,     -- 채용로봇URL
	WORK_ZIP          CHARACTER VARYING(10)  NULL,     -- 근무우편번호
	WORK_RDNMADR      CHARACTER VARYING(200) NULL,     -- 근무도로명주소
	WORK_BASS_ADRES   CHARACTER VARYING(200) NULL,     -- 근무기본주소
	WORK_DETAIL_ADRES CHARACTER VARYING(200) NULL,     -- 근무상세주소
	CREATE_DT         CHAR(8)       NOT NULL  -- 생성일자
);

-- 워크넷_구인_목록
/*
ALTER TABLE SRV_DT_WORKNET_MASTER
	ADD
		CONSTRAINT PK_SRV_DT_WORKNET_MASTER -- 워크넷_구인_목록 기본키
		PRIMARY KEY (
			JO_AUTH_NO -- 구인인증번호
		);
*/
-- 워크넷_구인_목록
COMMENT ON TABLE SRV_DT_WORKNET_MASTER IS '워크넷_구인_목록';

-- 구인인증번호
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.JO_AUTH_NO IS '구인인증번호';

-- 회사명
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.CORP_NM IS '회사명';

-- 사업자번호
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.BSNM_NO IS '사업자번호';

-- 채용제목
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.RECRU_TITLE IS '채용제목';

-- 임금형태원시
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.WAGE_TYPE_RAW IS '임금형태원시';

-- 급여원시
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.SALARY_RAW IS '급여원시';

-- 근무지역
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.WORK_REGION IS '근무지역';

-- 근무형태원시
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.WORK_TYPE_RAW IS '근무형태원시';

-- 최소학력
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.MIN_ACDMCR IS '최소학력';

-- 최대학력
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.MAX_ACDMCR IS '최대학력';

-- 경력원시
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.CAREER_RAW IS '경력원시';

-- 등록일자원시
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.REG_DT_RAW IS '등록일자원시';

-- 마감일자원시
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.CLOS_DT_RAW IS '마감일자원시';

-- 정보제공처
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.INFO_PROVD_OFFIC IS '정보제공처';

-- 채용로봇URL
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.RECRU_ROBOT_URL IS '채용로봇URL';

-- 근무우편번호
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.WORK_ZIP IS '근무우편번호';

-- 근무도로명주소
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.WORK_RDNMADR IS '근무도로명주소';

-- 근무기본주소
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.WORK_BASS_ADRES IS '근무기본주소';

-- 근무상세주소
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.WORK_DETAIL_ADRES IS '근무상세주소';

-- 생성일자
COMMENT ON COLUMN SRV_DT_WORKNET_MASTER.CREATE_DT IS '생성일자';

-- 워크넷_구인_목록 기본키
-- COMMENT ON INDEX PK_SRV_DT_WORKNET_MASTER IS '워크넷_구인_목록 기본키';

-- 워크넷_구인_목록 기본키
-- COMMENT ON CONSTRAINT SRV_DT_WORKNET_MASTER.PK_SRV_DT_WORKNET_MASTER IS '워크넷_구인_목록 기본키';

-- 워크넷_구인_상세
CREATE TABLE SRV_DT_WORKNET_DETAIL (
	JO_AUTH_NO              CHARACTER VARYING(20)   NOT NULL, -- 구인인증번호
	CORP_NM                 CHARACTER VARYING(100)  NOT NULL, -- 회사명
	MAIN_NM                 CHARACTER VARYING(100)  NULL,     -- 대표자명
	LABRR_CNT               CHARACTER VARYING(200)  NOT NULL, -- 근로자수
	CAP                     CHARACTER VARYING(200)  NULL, -- 자본금
	YEAR_SALES              CHARACTER VARYING(200)  NULL,     -- 연매출액
	BIZ_NM                  CHARACTER VARYING(1000)  NOT NULL, -- 업종명
	MAIN_BIZ_CONTENT        CHARACTER VARYING(1000) NULL,     -- 주요사업내용
	CORP_ADDR               CHARACTER VARYING(200)  NOT NULL, -- 회사주소
	CORP_HPAGE              CHARACTER VARYING(200)  NULL,     -- 회사홈페이지
	CORP_SZ_RAW             CHARACTER VARYING(200)  NOT NULL, -- 회사규모원시
	RCRIT_JSSFC_RAW         CHARACTER VARYING(200)  NOT NULL, -- 모집직종원시
	JO_TITLE                CHARACTER VARYING(200)  NULL,     -- 구인제목
	REL_JSSFC               CHARACTER VARYING(200)  NULL,     -- 관련직종
	DTY_CONTENT             CHARACTER VARYING(1000) NULL,     -- 직무내용
	RCEPT_CLOS_DT           CHARACTER VARYING(8)    NULL,     -- 접수마감일
	EMPLYM_TYPE_RAW         CHARACTER VARYING(200)  NOT NULL, -- 고용형태원시
	RCRIT_PSN_RAW           CHARACTER VARYING(200)  NOT NULL, -- 모집인원원시
	WAGE_CND                CHARACTER VARYING(200)  NOT NULL, -- 임금조건
	CAREER_CND              CHARACTER VARYING(200)  NULL,     -- 경력조건
	ACDMCR_RAW              CHARACTER VARYING(200)  NOT NULL, -- 학력원시
	FGGG                    CHARACTER VARYING(200)  NULL,     -- 외국어
	MAJOR                   CHARACTER VARYING(200)  NULL,     -- 전공
	QUALF_LCNS              CHARACTER VARYING(2000) NULL,     -- 자격면허
	MLTPWR_EXCPT_RECRU_HOPE CHARACTER VARYING(200)  NULL,     -- 병력특례채용희망
	CMPUTR_PRCUSE_ABLTY     CHARACTER VARYING(1000) NULL,     -- 컴퓨터활용능력
	PVLTRT_CND              CHARACTER VARYING(300)  NULL,     -- 우대조건
	ETC_PVLTRT_CND          CHARACTER VARYING(1000) NULL,     -- 기타우대조건
	RECRU_MTH               CHARACTER VARYING(200)  NULL,     -- 채용방법
	RCEPT_MTH               CHARACTER VARYING(500)  NULL,     -- 접수방법
	SUBMIT_PAPERS_PRPARE    CHARACTER VARYING(500)  NULL,     -- 제출서류준비
	ETC_GUIDANCE            CHARACTER VARYING(4000) NULL,     -- 기타안내
	WORK_INTSPT             CHARACTER VARYING(200)  NOT NULL, -- 근무예정지
	PSITN_IRSTT             CHARACTER VARYING(200)  NULL,     -- 소속산업단지
	NEARBY_ECLW_STATION     CHARACTER VARYING(500)  NULL,     -- 인근전철역
	WORK_TIME               CHARACTER VARYING(500)  NULL,     -- 근무시간
	ANNTY_FEINSR            CHARACTER VARYING(500)  NULL,     -- 연금4대보험
	RTRPAY                  CHARACTER VARYING(500)  NULL,     -- 퇴직금
	ETC_WLFARE              CHARACTER VARYING(500)  NULL,     -- 기타복리후생
	DSPSN_CVNTL             CHARACTER VARYING(500)  NULL,     -- 장애인편의시설
	RECRU_DEPT              CHARACTER VARYING(500)  NULL,     -- 채용부서
	TEL_NO                  CHARACTER VARYING(20)   NULL,     -- 전화번호
	FAX_NO                  CHARACTER VARYING(20)   NULL,     -- 팩스번호
	CREATE_DT               CHAR(8)        NULL      -- 생성일자
);

-- 워크넷_구인_상세
/*
ALTER TABLE SRV_DT_WORKNET_DETAIL
	ADD
		CONSTRAINT PK_SRV_DT_WORKNET_DETAIL -- 워크넷_구인_상세 기본키
		PRIMARY KEY (
			JO_AUTH_NO -- 구인인증번호
		);
		*/

-- 워크넷_구인_상세
COMMENT ON TABLE SRV_DT_WORKNET_DETAIL IS '워크넷_구인_상세';

-- 구인인증번호
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.JO_AUTH_NO IS '구인인증번호';

-- 회사명
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.CORP_NM IS '회사명';

-- 대표자명
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.MAIN_NM IS '대표자명';

-- 근로자수
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.LABRR_CNT IS '근로자수';

-- 자본금
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.CAP IS '자본금';

-- 연매출액
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.YEAR_SALES IS '연매출액';

-- 업종명
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.BIZ_NM IS '업종명';

-- 주요사업내용
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.MAIN_BIZ_CONTENT IS '주요사업내용';

-- 회사주소
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.CORP_ADDR IS '회사주소';

-- 회사홈페이지
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.CORP_HPAGE IS '회사홈페이지';

-- 회사규모원시
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.CORP_SZ_RAW IS '회사규모원시';

-- 모집직종원시
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.RCRIT_JSSFC_RAW IS '모집직종원시';

-- 구인제목
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.JO_TITLE IS '구인제목';

-- 관련직종
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.REL_JSSFC IS '관련직종';

-- 직무내용
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.DTY_CONTENT IS '직무내용';

-- 접수마감일
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.RCEPT_CLOS_DT IS '접수마감일';

-- 고용형태원시
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.EMPLYM_TYPE_RAW IS '고용형태원시';

-- 모집인원원시
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.RCRIT_PSN_RAW IS '모집인원원시';

-- 임금조건
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.WAGE_CND IS '임금조건';

-- 경력조건
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.CAREER_CND IS '경력조건';

-- 학력원시
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.ACDMCR_RAW IS '학력원시';

-- 외국어
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.FGGG IS '외국어';

-- 전공
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.MAJOR IS '전공';

-- 자격면허
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.QUALF_LCNS IS '자격면허';

-- 병력특례채용희망
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.MLTPWR_EXCPT_RECRU_HOPE IS '병력특례채용희망';

-- 컴퓨터활용능력
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.CMPUTR_PRCUSE_ABLTY IS '컴퓨터활용능력';

-- 우대조건
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.PVLTRT_CND IS '우대조건';

-- 기타우대조건
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.ETC_PVLTRT_CND IS '기타우대조건';

-- 채용방법
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.RECRU_MTH IS '채용방법';

-- 접수방법
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.RCEPT_MTH IS '접수방법';

-- 제출서류준비
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.SUBMIT_PAPERS_PRPARE IS '제출서류준비';

-- 기타안내
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.ETC_GUIDANCE IS '기타안내';

-- 근무예정지
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.WORK_INTSPT IS '근무예정지';

-- 소속산업단지
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.PSITN_IRSTT IS '소속산업단지';

-- 인근전철역
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.NEARBY_ECLW_STATION IS '인근전철역';

-- 근무시간
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.WORK_TIME IS '근무시간';

-- 연금4대보험
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.ANNTY_FEINSR IS '연금4대보험';

-- 퇴직금
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.RTRPAY IS '퇴직금';

-- 기타복리후생
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.ETC_WLFARE IS '기타복리후생';

-- 장애인편의시설
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.DSPSN_CVNTL IS '장애인편의시설';

-- 채용부서
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.RECRU_DEPT IS '채용부서';

-- 전화번호
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.TEL_NO IS '전화번호';

-- 팩스번호
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.FAX_NO IS '팩스번호';

-- 생성일자
COMMENT ON COLUMN SRV_DT_WORKNET_DETAIL.CREATE_DT IS '생성일자';

-- 워크넷_구인_상세 기본키
-- COMMENT ON INDEX PK_SRV_DT_WORKNET_DETAIL IS '워크넷_구인_상세 기본키';

-- 워크넷_구인_상세 기본키
-- COMMENT ON CONSTRAINT SRV_DT_WORKNET_DETAIL.PK_SRV_DT_WORKNET_DETAIL IS '워크넷_구인_상세 기본키';

-- 오늘의구인현황정제
CREATE TABLE SRV_DT_JOB_SM_REFINE (
	JO_NO            CHAR(20)      NOT NULL, -- 구인번호
	CORP_NM          CHARACTER VARYING(100) NOT NULL, -- 회사명
	BSNM_NO          CHAR(13)      NOT NULL, -- 사업자번호
	INDUST_CLASS     CHARACTER VARYING(6)   NOT NULL, -- 산업분류
	ENTRPRS_TYPE     CHAR(2)       NOT NULL, -- 기업형태
	CORP_SZ          CHARACTER VARYING(4)   NOT NULL, -- 회사규모
	LABRR_CNT        INTEGER       NOT NULL, -- 근로자수
	CORP_ADDR        CHARACTER VARYING(200) NOT NULL, -- 회사주소
	CAP              BIGINT        NOT NULL, -- 자본금
	MAIN_NM          CHARACTER VARYING(100)  NULL,     -- 대표자명
	YEAR_SALES       BIGINT        NULL,     -- 연매출액
	MAIN_BIZ_CONTENT CHARACTER VARYING(1000) NULL,     -- 주요사업내용
	CORP_HPAGE       CHARACTER VARYING(200) NULL,     -- 회사홈페이지
	RECRU_NM         CHARACTER VARYING(200) NOT NULL, -- 채용명
	CAREER           CHAR(1)       NOT NULL, -- 경력
	ACDMCR           CHAR(2)       NOT NULL, -- 학력
	WAGE_TYPE        CHAR(1)       NOT NULL, -- 임금형태
	SALARY           BIGINT        NOT NULL, -- 급여
	WORK_TYPE        CHAR(1)       NOT NULL, -- 근무형태
	EMPLYM_TYPE      CHARACTER VARYING(2)   NOT NULL, -- 고용형태
	RCRIT_JSSFC      CHARACTER VARYING(6)   NOT NULL, -- 모집직종
	RCRIT_PSN        INTEGER       NOT NULL, -- 모집인원
	REG_DT           CHAR(8)       NOT NULL, -- 등록일자
	CLOS_DT          CHAR(8)       NOT NULL, -- 마감일자
	JO_AUTH_NO       CHARACTER VARYING(20)  NULL,     -- 구인인증번호
	PBLANC_NO        CHARACTER VARYING(20)  NULL,     -- 공고번호
	JO_DATA_DIV      CHAR(1)       NOT NULL, -- 구인자료구분
	JO_DATA_KEY      CHARACTER VARYING(20)  NOT NULL, -- 구인자료키
	WORK_REGION      CHARACTER VARYING(200) NOT NULL, -- 근무지역
	WORK_ADDR        CHARACTER VARYING(200) NOT NULL, -- 근무주소
	SIDO_CD          CHAR(2)       NOT NULL, -- 시도코드
	SGG_CD           CHAR(3)       NOT NULL, -- 시군구코드
	EMDONG_CD        CHAR(2)       NOT NULL, -- 읍면동코드
	CREATE_DT        CHAR(8)       NOT NULL  -- 생성일자
);

-- 오늘의구인현황정제
ALTER TABLE SRV_DT_JOB_SM_REFINE
	ADD
		CONSTRAINT PK_SRV_DT_JOB_SM_REFINE -- 오늘의구인현황정제 기본키
		PRIMARY KEY (
			JO_NO -- 구인번호
		);

-- 오늘의구인현황정제
COMMENT ON TABLE SRV_DT_JOB_SM_REFINE IS '오늘의구인현황정제';

-- 구인번호
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.JO_NO IS '구인번호';

-- 회사명
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.CORP_NM IS '회사명';

-- 사업자번호
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.BSNM_NO IS '사업자번호';

-- 산업분류
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.INDUST_CLASS IS '산업분류';

-- 기업형태
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.ENTRPRS_TYPE IS '기업형태';

-- 회사규모
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.CORP_SZ IS '회사규모';

-- 근로자수
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.LABRR_CNT IS '근로자수';

-- 회사주소
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.CORP_ADDR IS '회사주소';

-- 자본금
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.CAP IS '자본금';

-- 대표자명
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.MAIN_NM IS '대표자명';

-- 연매출액
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.YEAR_SALES IS '연매출액';

-- 주요사업내용
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.MAIN_BIZ_CONTENT IS '주요사업내용';

-- 회사홈페이지
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.CORP_HPAGE IS '회사홈페이지';

-- 채용명
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.RECRU_NM IS '채용명';

-- 경력
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.CAREER IS '경력';

-- 학력
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.ACDMCR IS '학력';

-- 임금형태
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.WAGE_TYPE IS '임금형태';

-- 급여
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.SALARY IS '급여';

-- 근무형태
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.WORK_TYPE IS '근무형태';

-- 고용형태
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.EMPLYM_TYPE IS '고용형태';

-- 모집직종
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.RCRIT_JSSFC IS '모집직종';

-- 모집인원
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.RCRIT_PSN IS '모집인원';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.REG_DT IS '등록일자';

-- 마감일자
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.CLOS_DT IS '마감일자';

-- 구인인증번호
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.JO_AUTH_NO IS '구인인증번호';

-- 공고번호
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.PBLANC_NO IS '공고번호';

-- 구인자료구분
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.JO_DATA_DIV IS '구인자료구분';

-- 구인자료키
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.JO_DATA_KEY IS '구인자료키';

-- 근무지역
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.WORK_REGION IS '근무지역';

-- 근무주소
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.WORK_ADDR IS '근무주소';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.EMDONG_CD IS '읍면동코드';

-- 생성일자
COMMENT ON COLUMN SRV_DT_JOB_SM_REFINE.CREATE_DT IS '생성일자';

-- 오늘의구인현황정제 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_SM_REFINE IS '오늘의구인현황정제 기본키';

-- 오늘의구인현황정제 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_SM_REFINE.PK_SRV_DT_JOB_SM_REFINE IS '오늘의구인현황정제 기본키';

-- 희망지역_구인_현황
CREATE TABLE SRV_DT_JOB_HOPE_AREA_SM (
	REG_DT        CHAR(8) NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2) NOT NULL, -- 시도코드
	SGG_CD        CHAR(3) NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2) NOT NULL, -- 읍면동코드
	JO_CNT        INTEGER NOT NULL, -- 구인건수
	CORP_CNT      INTEGER NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER NOT NULL  -- 모집인원수
);

-- 희망지역_구인_현황
ALTER TABLE SRV_DT_JOB_HOPE_AREA_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_HOPE_AREA_SM -- 희망지역_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,    -- 등록일자
			SIDO_CD,   -- 시도코드
			SGG_CD,    -- 시군구코드
			EMDONG_CD, -- 읍면동코드
			JO_CNT     -- 구인건수
		);

-- 희망지역_구인_현황
COMMENT ON TABLE SRV_DT_JOB_HOPE_AREA_SM IS '희망지역_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_HOPE_AREA_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_HOPE_AREA_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_HOPE_AREA_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_HOPE_AREA_SM.EMDONG_CD IS '읍면동코드';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_HOPE_AREA_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_HOPE_AREA_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_HOPE_AREA_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 희망지역_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_HOPE_AREA_SM IS '희망지역_구인_현황 기본키';

-- 희망지역_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_HOPE_AREA_SM.PK_SRV_DT_JOB_HOPE_AREA_SM IS '희망지역_구인_현황 기본키';

-- 기업형태_구인_현황
CREATE TABLE SRV_DT_JOB_ENTRPRS_TYPE_SM (
	REG_DT        CHAR(8) NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2) NOT NULL, -- 시도코드
	SGG_CD        CHAR(3) NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2) NOT NULL, -- 읍면동코드
	ENTRPRS_TYPE  CHAR(2) NOT NULL, -- 기업형태
	JO_CNT        INTEGER NOT NULL, -- 구인건수
	CORP_CNT      INTEGER NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER NOT NULL  -- 모집인원수
);

-- 기업형태_구인_현황
ALTER TABLE SRV_DT_JOB_ENTRPRS_TYPE_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_ENTRPRS_TYPE_SM -- 기업형태_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,       -- 등록일자
			SIDO_CD,      -- 시도코드
			SGG_CD,       -- 시군구코드
			EMDONG_CD,    -- 읍면동코드
			ENTRPRS_TYPE  -- 기업형태
		);

-- 기업형태_구인_현황
COMMENT ON TABLE SRV_DT_JOB_ENTRPRS_TYPE_SM IS '기업형태_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_ENTRPRS_TYPE_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_ENTRPRS_TYPE_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_ENTRPRS_TYPE_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_ENTRPRS_TYPE_SM.EMDONG_CD IS '읍면동코드';

-- 기업형태
COMMENT ON COLUMN SRV_DT_JOB_ENTRPRS_TYPE_SM.ENTRPRS_TYPE IS '기업형태';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_ENTRPRS_TYPE_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_ENTRPRS_TYPE_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_ENTRPRS_TYPE_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 기업형태_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_ENTRPRS_TYPE_SM IS '기업형태_구인_현황 기본키';

-- 기업형태_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_ENTRPRS_TYPE_SM.PK_SRV_DT_JOB_ENTRPRS_TYPE_SM IS '기업형태_구인_현황 기본키';

-- 회사규모_구인_현황
CREATE TABLE SRV_DT_JOB_CORP_SZ_SM (
	REG_DT        CHAR(8)     NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2)     NOT NULL, -- 시도코드
	SGG_CD        CHAR(3)     NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2)     NOT NULL, -- 읍면동코드
	CORP_SZ       CHARACTER VARYING(4) NOT NULL, -- 회사규모
	JO_CNT        INTEGER     NOT NULL, -- 구인건수
	CORP_CNT      INTEGER     NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER     NOT NULL  -- 모집인원수
);

-- 회사규모_구인_현황
ALTER TABLE SRV_DT_JOB_CORP_SZ_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_CORP_SZ_SM -- 회사규모_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,    -- 등록일자
			SIDO_CD,   -- 시도코드
			SGG_CD,    -- 시군구코드
			EMDONG_CD, -- 읍면동코드
			CORP_SZ    -- 회사규모
		);

-- 회사규모_구인_현황
COMMENT ON TABLE SRV_DT_JOB_CORP_SZ_SM IS '회사규모_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_CORP_SZ_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_CORP_SZ_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_CORP_SZ_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_CORP_SZ_SM.EMDONG_CD IS '읍면동코드';

-- 회사규모
COMMENT ON COLUMN SRV_DT_JOB_CORP_SZ_SM.CORP_SZ IS '회사규모';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_CORP_SZ_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_CORP_SZ_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_CORP_SZ_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 회사규모_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_CORP_SZ_SM IS '회사규모_구인_현황 기본키';

-- 회사규모_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_CORP_SZ_SM.PK_SRV_DT_JOB_CORP_SZ_SM IS '회사규모_구인_현황 기본키';

-- 산업분류_구인_현황
CREATE TABLE SRV_DT_JOB_INDUST_CLASS_SM (
	REG_DT        CHAR(8)     NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2)     NOT NULL, -- 시도코드
	SGG_CD        CHAR(3)     NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2)     NOT NULL, -- 읍면동코드
	INDUST_CLASS  CHARACTER VARYING(6) NOT NULL, -- 산업분류
	JO_CNT        INTEGER     NOT NULL, -- 구인건수
	CORP_CNT      INTEGER     NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER     NOT NULL  -- 모집인원수
);

-- 산업분류_구인_현황
ALTER TABLE SRV_DT_JOB_INDUST_CLASS_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_INDUST_CLASS_SM -- 산업분류_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,       -- 등록일자
			SIDO_CD,      -- 시도코드
			SGG_CD,       -- 시군구코드
			EMDONG_CD,    -- 읍면동코드
			INDUST_CLASS  -- 산업분류
		);

-- 산업분류_구인_현황
COMMENT ON TABLE SRV_DT_JOB_INDUST_CLASS_SM IS '산업분류_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_INDUST_CLASS_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_INDUST_CLASS_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_INDUST_CLASS_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_INDUST_CLASS_SM.EMDONG_CD IS '읍면동코드';

-- 산업분류
COMMENT ON COLUMN SRV_DT_JOB_INDUST_CLASS_SM.INDUST_CLASS IS '산업분류';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_INDUST_CLASS_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_INDUST_CLASS_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_INDUST_CLASS_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 산업분류_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_INDUST_CLASS_SM IS '산업분류_구인_현황 기본키';

-- 산업분류_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_INDUST_CLASS_SM.PK_SRV_DT_JOB_INDUST_CLASS_SM IS '산업분류_구인_현황 기본키';

-- 직종분류_구인_현황
CREATE TABLE SRV_DT_JOB_JSSFC_SM (
	REG_DT        CHAR(8)     NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2)     NOT NULL, -- 시도코드
	SGG_CD        CHAR(3)     NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2)     NOT NULL, -- 읍면동코드
	JSSFC_CLASS   CHARACTER VARYING(6) NOT NULL, -- 직종분류
	JO_CNT        INTEGER     NOT NULL, -- 구인건수
	CORP_CNT      INTEGER     NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER     NOT NULL  -- 모집인원수
);

-- 직종분류_구인_현황
ALTER TABLE SRV_DT_JOB_JSSFC_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_JSSFC_SM -- 직종분류_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,      -- 등록일자
			SIDO_CD,     -- 시도코드
			SGG_CD,      -- 시군구코드
			EMDONG_CD,   -- 읍면동코드
			JSSFC_CLASS  -- 직종분류
		);

-- 직종분류_구인_현황
COMMENT ON TABLE SRV_DT_JOB_JSSFC_SM IS '직종분류_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_JSSFC_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_JSSFC_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_JSSFC_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_JSSFC_SM.EMDONG_CD IS '읍면동코드';

-- 직종분류
COMMENT ON COLUMN SRV_DT_JOB_JSSFC_SM.JSSFC_CLASS IS '직종분류';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_JSSFC_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_JSSFC_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_JSSFC_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 직종분류_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_JSSFC_SM IS '직종분류_구인_현황 기본키';

-- 직종분류_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_JSSFC_SM.PK_SRV_DT_JOB_JSSFC_SM IS '직종분류_구인_현황 기본키';

-- 급여수준_구인_현황
CREATE TABLE SRV_DT_JOB_SALARY_SM (
	REG_DT        CHAR(8) NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2) NOT NULL, -- 시도코드
	SGG_CD        CHAR(3) NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2) NOT NULL, -- 읍면동코드
	WAGE_TYPE     CHAR(1) NOT NULL, -- 임금형태
	SALARY        BIGINT  NOT NULL, -- 급여
	JO_CNT        INTEGER NOT NULL, -- 구인건수
	CORP_CNT      INTEGER NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER NOT NULL  -- 모집인원수
);

-- 급여수준_구인_현황
ALTER TABLE SRV_DT_JOB_SALARY_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_SALARY_SM -- 급여수준_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,    -- 등록일자
			SIDO_CD,   -- 시도코드
			SGG_CD,    -- 시군구코드
			EMDONG_CD, -- 읍면동코드
			WAGE_TYPE,  -- 임금형태
			SALARY
		);

-- 급여수준_구인_현황
COMMENT ON TABLE SRV_DT_JOB_SALARY_SM IS '급여수준_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_SALARY_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_SALARY_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_SALARY_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_SALARY_SM.EMDONG_CD IS '읍면동코드';

-- 임금형태
COMMENT ON COLUMN SRV_DT_JOB_SALARY_SM.WAGE_TYPE IS '임금형태';

-- 급여
COMMENT ON COLUMN SRV_DT_JOB_SALARY_SM.SALARY IS '급여';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_SALARY_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_SALARY_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_SALARY_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 급여수준_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_SALARY_SM IS '급여수준_구인_현황 기본키';

-- 급여수준_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_SALARY_SM.PK_SRV_DT_JOB_SALARY_SM IS '급여수준_구인_현황 기본키';

-- 고용형태_구인_현황
CREATE TABLE SRV_DT_JOB_EMPLYM_TYPE_SM (
	REG_DT        CHAR(8)     NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2)     NOT NULL, -- 시도코드
	SGG_CD        CHAR(3)     NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2)     NOT NULL, -- 읍면동코드
	EMPLYM_TYPE   CHARACTER VARYING(2) NOT NULL, -- 고용형태
	JO_CNT        INTEGER     NOT NULL, -- 구인건수
	CORP_CNT      INTEGER     NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER     NOT NULL  -- 모집인원수
);

-- 고용형태_구인_현황
ALTER TABLE SRV_DT_JOB_EMPLYM_TYPE_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_EMPLYM_TYPE_SM -- 고용형태_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,      -- 등록일자
			SIDO_CD,     -- 시도코드
			SGG_CD,      -- 시군구코드
			EMDONG_CD,   -- 읍면동코드
			EMPLYM_TYPE  -- 고용형태
		);

-- 고용형태_구인_현황
COMMENT ON TABLE SRV_DT_JOB_EMPLYM_TYPE_SM IS '고용형태_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_EMPLYM_TYPE_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_EMPLYM_TYPE_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_EMPLYM_TYPE_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_EMPLYM_TYPE_SM.EMDONG_CD IS '읍면동코드';

-- 고용형태
COMMENT ON COLUMN SRV_DT_JOB_EMPLYM_TYPE_SM.EMPLYM_TYPE IS '고용형태';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_EMPLYM_TYPE_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_EMPLYM_TYPE_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_EMPLYM_TYPE_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 고용형태_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_EMPLYM_TYPE_SM IS '고용형태_구인_현황 기본키';

-- 고용형태_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_EMPLYM_TYPE_SM.PK_SRV_DT_JOB_EMPLYM_TYPE_SM IS '고용형태_구인_현황 기본키';

-- 근무형태_구인_현황
CREATE TABLE SRV_DT_JOB_WORK_TYPE_SM (
	REG_DT        CHAR(8) NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2) NOT NULL, -- 시도코드
	SGG_CD        CHAR(3) NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2) NOT NULL, -- 읍면동코드
	WORK_TYPE     CHAR(1) NOT NULL, -- 근무형태
	JO_CNT        INTEGER NOT NULL, -- 구인건수
	CORP_CNT      INTEGER NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER NOT NULL  -- 모집인원수
);

-- 근무형태_구인_현황
ALTER TABLE SRV_DT_JOB_WORK_TYPE_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_WORK_TYPE_SM -- 근무형태_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,    -- 등록일자
			SIDO_CD,   -- 시도코드
			SGG_CD,    -- 시군구코드
			EMDONG_CD, -- 읍면동코드
			WORK_TYPE  -- 근무형태
		);

-- 근무형태_구인_현황
COMMENT ON TABLE SRV_DT_JOB_WORK_TYPE_SM IS '근무형태_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_WORK_TYPE_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_WORK_TYPE_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_WORK_TYPE_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_WORK_TYPE_SM.EMDONG_CD IS '읍면동코드';

-- 근무형태
COMMENT ON COLUMN SRV_DT_JOB_WORK_TYPE_SM.WORK_TYPE IS '근무형태';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_WORK_TYPE_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_WORK_TYPE_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_WORK_TYPE_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 근무형태_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_WORK_TYPE_SM IS '근무형태_구인_현황 기본키';

-- 근무형태_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_WORK_TYPE_SM.PK_SRV_DT_JOB_WORK_TYPE_SM IS '근무형태_구인_현황 기본키';

-- 학력_구인_현황
CREATE TABLE SRV_DT_JOB_ACDMCR_SM (
	REG_DT        CHAR(8) NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2) NOT NULL, -- 시도코드
	SGG_CD        CHAR(3) NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2) NOT NULL, -- 읍면동코드
	ACDMCR        CHAR(2) NOT NULL, -- 학력
	JO_CNT        INTEGER NOT NULL, -- 구인건수
	CORP_CNT      INTEGER NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER NOT NULL  -- 모집인원수
);

-- 학력_구인_현황
ALTER TABLE SRV_DT_JOB_ACDMCR_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_ACDMCR_SM -- 학력_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,    -- 등록일자
			SIDO_CD,   -- 시도코드
			SGG_CD,    -- 시군구코드
			EMDONG_CD, -- 읍면동코드
			ACDMCR     -- 학력
		);

-- 학력_구인_현황
COMMENT ON TABLE SRV_DT_JOB_ACDMCR_SM IS '학력_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_ACDMCR_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_ACDMCR_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_ACDMCR_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_ACDMCR_SM.EMDONG_CD IS '읍면동코드';

-- 학력
COMMENT ON COLUMN SRV_DT_JOB_ACDMCR_SM.ACDMCR IS '학력';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_ACDMCR_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_ACDMCR_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_ACDMCR_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 학력_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_ACDMCR_SM IS '학력_구인_현황 기본키';

-- 학력_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_ACDMCR_SM.PK_SRV_DT_JOB_ACDMCR_SM IS '학력_구인_현황 기본키';

-- 경력_구인_현황
CREATE TABLE SRV_DT_JOB_CAREER_SM (
	REG_DT        CHAR(8) NOT NULL, -- 등록일자
	SIDO_CD       CHAR(2) NOT NULL, -- 시도코드
	SGG_CD        CHAR(3) NOT NULL, -- 시군구코드
	EMDONG_CD     CHAR(2) NOT NULL, -- 읍면동코드
	CAREER        CHAR(1) NOT NULL, -- 경력
	JO_CNT        INTEGER NOT NULL, -- 구인건수
	CORP_CNT      INTEGER NOT NULL, -- 업체수
	RCRIT_PSN_CNT INTEGER NOT NULL  -- 모집인원수
);

-- 경력_구인_현황
ALTER TABLE SRV_DT_JOB_CAREER_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_CAREER_SM -- 경력_구인_현황 기본키
		PRIMARY KEY (
			REG_DT,    -- 등록일자
			SIDO_CD,   -- 시도코드
			SGG_CD,    -- 시군구코드
			EMDONG_CD, -- 읍면동코드
			CAREER     -- 경력
		);

-- 경력_구인_현황
COMMENT ON TABLE SRV_DT_JOB_CAREER_SM IS '경력_구인_현황';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_CAREER_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_CAREER_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_CAREER_SM.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_CAREER_SM.EMDONG_CD IS '읍면동코드';

-- 경력
COMMENT ON COLUMN SRV_DT_JOB_CAREER_SM.CAREER IS '경력';

-- 구인건수
COMMENT ON COLUMN SRV_DT_JOB_CAREER_SM.JO_CNT IS '구인건수';

-- 업체수
COMMENT ON COLUMN SRV_DT_JOB_CAREER_SM.CORP_CNT IS '업체수';

-- 모집인원수
COMMENT ON COLUMN SRV_DT_JOB_CAREER_SM.RCRIT_PSN_CNT IS '모집인원수';

-- 경력_구인_현황 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_CAREER_SM IS '경력_구인_현황 기본키';

-- 경력_구인_현황 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_CAREER_SM.PK_SRV_DT_JOB_CAREER_SM IS '경력_구인_현황 기본키';

-- 구인현황판
CREATE TABLE SRV_DT_JOB_BOARD_SM (
	REG_DT             CHAR(8) NOT NULL, -- 등록일자
	SIDO_CD            CHAR(2) NOT NULL, -- 시도코드
	SGG_CD             CHAR(3) NOT NULL, -- 시군구코드
	ALL_JO_CNT         INTEGER NOT NULL, -- 전체구인수
	ALL_CORP_CNT       INTEGER NOT NULL, -- 전체업체수
	ALL_RCRIT_PSN_CNT  INTEGER NOT NULL, -- 전체모집인원수
	NEW_JO_CNT         INTEGER NOT NULL, -- 신규구인수
	NEW_CORP_CNT       INTEGER NOT NULL, -- 신규업체수
	NEW_RCRIT_PSN_CNT  INTEGER NOT NULL, -- 신규모집인원수
	CLOS_JO_CNT        INTEGER NOT NULL, -- 마감구인수
	CLOS_CORP_CNT      INTEGER NOT NULL, -- 마감업체수
	CLOS_RCRIT_PSN_CNT INTEGER NOT NULL  -- 마감모집인원수
);

-- 구인현황판
ALTER TABLE SRV_DT_JOB_BOARD_SM
	ADD
		CONSTRAINT PK_SRV_DT_JOB_BOARD_SM -- 구인현황판 기본키
		PRIMARY KEY (
			REG_DT,  -- 등록일자
			SIDO_CD, -- 시도코드
			SGG_CD   -- 시군구코드
		);

-- 구인현황판
COMMENT ON TABLE SRV_DT_JOB_BOARD_SM IS '구인현황판';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.REG_DT IS '등록일자';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.SGG_CD IS '시군구코드';

-- 전체구인수
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.ALL_JO_CNT IS '전체구인수';

-- 전체업체수
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.ALL_CORP_CNT IS '전체업체수';

-- 전체모집인원수
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.ALL_RCRIT_PSN_CNT IS '전체모집인원수';

-- 신규구인수
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.NEW_JO_CNT IS '신규구인수';

-- 신규업체수
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.NEW_CORP_CNT IS '신규업체수';

-- 신규모집인원수
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.NEW_RCRIT_PSN_CNT IS '신규모집인원수';

-- 마감구인수
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.CLOS_JO_CNT IS '마감구인수';

-- 마감업체수
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.CLOS_CORP_CNT IS '마감업체수';

-- 마감모집인원수
COMMENT ON COLUMN SRV_DT_JOB_BOARD_SM.CLOS_RCRIT_PSN_CNT IS '마감모집인원수';

-- 구인현황판 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_BOARD_SM IS '구인현황판 기본키';

-- 구인현황판 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_BOARD_SM.PK_SRV_DT_JOB_BOARD_SM IS '구인현황판 기본키';

-- 인크루트_구인_수집
CREATE TABLE SRV_DT_INCRUIT_JSON (
	PBLANC_NO           CHARACTER VARYING(20)   NOT NULL, -- 공고번호
	ENTRPRS_NM          CHARACTER VARYING(500)  NOT NULL, -- 기업명
	BIZ_NM              CHARACTER VARYING(1000) NOT NULL, -- 업종명
	CORP_ADDR           CHARACTER VARYING(200)  NOT NULL, -- 회사주소
	BSNM_NO             CHAR(13)       NULL,     -- 사업자번호
	ENTRPRS_TYPE_RAW    CHARACTER VARYING(200)  NULL,     -- 기업형태원시
	NWMB_YN             CHARACTER VARYING(10)   NULL,     -- 신입여부
	CAREER_YN           CHARACTER VARYING(20)   NOT NULL, -- 경력여부
	RCRIT_CLOS          CHARACTER VARYING(10)   NULL,     -- 모집마감
	CLOS_DT_RAW         CHARACTER VARYING(50)   NULL,     -- 마감일자원시
	RCRIT_DT            CHARACTER VARYING(10)   NOT NULL, -- 모집일자
	CAREER_RAW          CHARACTER VARYING(100)  NOT NULL, -- 경력원시
	PBLANC_NM           CHARACTER VARYING(1000) NOT NULL, -- 공고명
	RCRIT_JSSFC_LIST    CHARACTER VARYING(3000) NOT NULL, -- 모집직종목록
	RCRIT_REGION_LIST   CHARACTER VARYING(1000) NULL,     -- 모집지역목록
	ANSLRY_1            CHARACTER VARYING(100)  NOT NULL, -- 연봉1
	ANSLRY_2            CHARACTER VARYING(100)  NOT NULL, -- 연봉2
	ANSLRY_DSCSS        CHARACTER VARYING(10)   NOT NULL, -- 연봉협의
	EMPLYM_TYPE_RAW     CHARACTER VARYING(200)  NOT NULL, -- 고용형태원시
	ACDMCR_RAW          CHARACTER VARYING(200)  NOT NULL, -- 학력원시
	RCRIT_PSN_RAW       CHARACTER VARYING(200)  NOT NULL, -- 모집인원원시
	QUALF_LCNS          CHARACTER VARYING(2000) NULL,     -- 자격면허
	RCRIT_START_DT      CHARACTER VARYING(20)   NULL,     -- 모집시작일
	NEARBY_ECLW_STATION CHARACTER VARYING(500)  NULL,     -- 인근전철역
	PBLANC_URL          CHARACTER VARYING(200)  NULL,     -- 공고URL
	CREATE_DT           CHAR(8)        NOT NULL  -- 생성일자
);

-- 인크루트_구인_수집
/*
ALTER TABLE SRV_DT_INCRUIT_JSON
	ADD
		CONSTRAINT PK_SRV_DT_INCRUIT_JSON -- 인크루트_구인_수집 기본키
		PRIMARY KEY (
			PBLANC_NO -- 공고번호
		);
*/
-- 인크루트_구인_수집
COMMENT ON TABLE SRV_DT_INCRUIT_JSON IS '인크루트_구인_수집';

-- 공고번호
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.PBLANC_NO IS '공고번호';

-- 기업명
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.ENTRPRS_NM IS '기업명';

-- 업종명
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.BIZ_NM IS '업종명';

-- 회사주소
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.CORP_ADDR IS '회사주소';

-- 사업자번호
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.BSNM_NO IS '사업자번호';

-- 기업형태원시
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.ENTRPRS_TYPE_RAW IS '기업형태원시';

-- 신입여부
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.NWMB_YN IS '신입여부';

-- 경력여부
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.CAREER_YN IS '경력여부';

-- 모집마감
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.RCRIT_CLOS IS '모집마감';

-- 마감일자원시
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.CLOS_DT_RAW IS '마감일자원시';

-- 모집일자
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.RCRIT_DT IS '모집일자';

-- 경력원시
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.CAREER_RAW IS '경력원시';

-- 공고명
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.PBLANC_NM IS '공고명';

-- 모집직종목록
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.RCRIT_JSSFC_LIST IS '모집직종목록';

-- 모집지역목록
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.RCRIT_REGION_LIST IS '모집지역목록';

-- 연봉1
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.ANSLRY_1 IS '연봉1';

-- 연봉2
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.ANSLRY_2 IS '연봉2';

-- 연봉협의
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.ANSLRY_DSCSS IS '연봉협의';

-- 고용형태원시
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.EMPLYM_TYPE_RAW IS '고용형태원시';

-- 학력원시
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.ACDMCR_RAW IS '학력원시';

-- 모집인원원시
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.RCRIT_PSN_RAW IS '모집인원원시';

-- 자격면허
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.QUALF_LCNS IS '자격면허';

-- 모집시작일
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.RCRIT_START_DT IS '모집시작일';

-- 인근전철역
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.NEARBY_ECLW_STATION IS '인근전철역';

-- 공고URL
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.PBLANC_URL IS '공고URL';

-- 생성일자
COMMENT ON COLUMN SRV_DT_INCRUIT_JSON.CREATE_DT IS '생성일자';

-- 인크루트_구인_수집 기본키
-- COMMENT ON INDEX PK_SRV_DT_INCRUIT_JSON IS '인크루트_구인_수집 기본키';

-- 인크루트_구인_수집 기본키
-- COMMENT ON CONSTRAINT SRV_DT_INCRUIT_JSON.PK_SRV_DT_INCRUIT_JSON IS '인크루트_구인_수집 기본키';

-- 일자리통계자료수집
CREATE TABLE SRV_DT_KOSIS_DATA (
	LINK_ID_SEQ   CHAR(11)      NOT NULL, -- 식별자
	ITM_ID        CHARACTER VARYING(50)  NOT NULL, -- 아이템식별자
	ORG_ID        CHARACTER VARYING(5)   NOT NULL, -- 조직식별자
	TBL_ID        CHARACTER VARYING(50)  NOT NULL, -- 테이블식별자
	DT            CHARACTER VARYING(30)  NOT NULL, -- 값데이터
	LINK_ID       CHARACTER VARYING(10)  NOT NULL, -- 연계ID
	PRD_DE        CHARACTER VARYING(20)  NOT NULL, -- 수록시점
	C1            CHARACTER VARYING(50)  NOT NULL, -- 분류1
	CREATE_DT     CHAR(8)       NOT NULL, -- 생성일자
	PRD_SE        CHARACTER VARYING(20)  NULL,     -- 수록주기
	ITM_NM        CHARACTER VARYING(200) NULL,     -- 아이템명칭
	ITM_NM_ENG    CHARACTER VARYING(300) NULL,     -- 아이템명칭영어
	TBL_NM        CHARACTER VARYING(300) NULL,     -- 테이블명칭
	UNIT_NM       CHARACTER VARYING(50)  NULL,     -- 단위명
	UNIT_NM_ENG   CHARACTER VARYING(200) NULL,     -- 단위명영문
	C1_NM         CHARACTER VARYING(200) NULL,     -- 분류1명
	C1_NM_ENG     CHARACTER VARYING(300) NULL,     -- 분류1명영문
	C1_OBJ_NM     CHARACTER VARYING(200) NULL,     -- 분류값1명
	C1_OBJ_NM_ENG CHARACTER VARYING(300) NULL,     -- 분류값1명영문
	C2            CHARACTER VARYING(50)  NULL,     -- 분류2
	C2_NM         CHARACTER VARYING(200) NULL,     -- 분류2명
	C2_NM_ENG     CHARACTER VARYING(300) NULL,     -- 분류2명영문
	C2_OBJ_NM     CHARACTER VARYING(200) NULL,     -- 분류값2명
	C2_OBJ_NM_ENG CHARACTER VARYING(300) NULL,     -- 분류값2명영문
	C3            CHARACTER VARYING(50)  NULL,     -- 분류3
	C3_NM         CHARACTER VARYING(200) NULL,     -- 분류3명
	C3_NM_ENG     CHARACTER VARYING(300) NULL,     -- 분류3명영문
	C3_OBJ_NM     CHARACTER VARYING(200) NULL,     -- 분류값3명
	C3_OBJ_NM_ENG CHARACTER VARYING(300) NULL      -- 분류값3명영문
);

-- 일자리통계자료수집
ALTER TABLE SRV_DT_KOSIS_DATA
	ADD
		CONSTRAINT PK_SRV_DT_KOSIS_DATA -- 일자리통계자료수집 기본키
		PRIMARY KEY (
			LINK_ID_SEQ
		);
		
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.LINK_ID_SEQ IS '링크아이디식별자';
-- 일자리통계자료수집
COMMENT ON TABLE SRV_DT_KOSIS_DATA IS '일자리통계자료수집';

-- 아이템식별자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.ITM_ID IS '아이템식별자';

-- 조직식별자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.ORG_ID IS '조직식별자';

-- 테이블식별자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.TBL_ID IS '테이블식별자';

-- 값데이터
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.DT IS '값데이터';

-- 연계ID
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.LINK_ID IS '연계ID';

-- 수록시점
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.PRD_DE IS '수록시점';

-- 분류1
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C1 IS '분류1';

-- 생성일자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.CREATE_DT IS '생성일자';

-- 수록주기
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.PRD_SE IS '수록주기';

-- 아이템명칭
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.ITM_NM IS '아이템명칭';

-- 아이템명칭영어
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.ITM_NM_ENG IS '아이템명칭영어';

-- 테이블명칭
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.TBL_NM IS '테이블명칭';

-- 단위명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.UNIT_NM IS '단위명';

-- 단위명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.UNIT_NM_ENG IS '단위명영문';

-- 분류1명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C1_NM IS '분류1명';

-- 분류1명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C1_NM_ENG IS '분류1명영문';

-- 분류값1명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C1_OBJ_NM IS '분류값1명';

-- 분류값1명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C1_OBJ_NM_ENG IS '분류값1명영문';

-- 분류2
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C2 IS '분류2';

-- 분류2명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C2_NM IS '분류2명';

-- 분류2명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C2_NM_ENG IS '분류2명영문';

-- 분류값2명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C2_OBJ_NM IS '분류값2명';

-- 분류값2명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C2_OBJ_NM_ENG IS '분류값2명영문';

-- 분류3
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C3 IS '분류3';

-- 분류3명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C3_NM IS '분류3명';

-- 분류3명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C3_NM_ENG IS '분류3명영문';

-- 분류값3명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C3_OBJ_NM IS '분류값3명';

-- 분류값3명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA.C3_OBJ_NM_ENG IS '분류값3명영문';

-- 일자리통계자료수집 기본키
--COMMENT ON INDEX PK_SRV_DT_KOSIS_DATA IS '일자리통계자료수집 기본키';

-- 일자리통계자료수집 기본키
-- COMMENT ON CONSTRAINT SRV_DT_KOSIS_DATA.PK_SRV_DT_KOSIS_DATA IS '일자리통계자료수집 기본키';

-- 오늘의구인현황중복제거
CREATE TABLE SRV_DT_JOB_SM_DUPL_REMOVE (
	JO_NO            CHAR(20)      NOT NULL, -- 구인번호
	CORP_NM          CHARACTER VARYING(100) NOT NULL, -- 회사명
	BSNM_NO          CHAR(13)      NOT NULL, -- 사업자번호
	INDUST_CLASS     CHARACTER VARYING(6)   NOT NULL, -- 산업분류
	ENTRPRS_TYPE     CHAR(2)       NOT NULL, -- 기업형태
	CORP_SZ          CHARACTER VARYING(4)   NOT NULL, -- 회사규모
	LABRR_CNT        INTEGER       NOT NULL, -- 근로자수
	CORP_ADDR        CHARACTER VARYING(200) NOT NULL, -- 회사주소
	CAP              BIGINT        NOT NULL, -- 자본금
	MAIN_NM          CHARACTER VARYING(100)  NULL,     -- 대표자명
	YEAR_SALES       BIGINT        NULL,     -- 연매출액
	MAIN_BIZ_CONTENT CHARACTER VARYING(1000) NULL,     -- 주요사업내용
	CORP_HPAGE       CHARACTER VARYING(200) NULL,     -- 회사홈페이지
	RECRU_NM         CHARACTER VARYING(200) NOT NULL, -- 채용명
	CAREER           CHAR(1)       NOT NULL, -- 경력
	ACDMCR           CHAR(2)       NOT NULL, -- 학력
	WAGE_TYPE        CHAR(1)       NOT NULL, -- 임금형태
	SALARY           BIGINT        NOT NULL, -- 급여
	WORK_TYPE        CHAR(1)       NOT NULL, -- 근무형태
	EMPLYM_TYPE      CHARACTER VARYING(2)   NOT NULL, -- 고용형태
	RCRIT_JSSFC      CHARACTER VARYING(6)   NOT NULL, -- 모집직종
	RCRIT_PSN        INTEGER       NOT NULL, -- 모집인원
	REG_DT           CHAR(8)       NOT NULL, -- 등록일자
	CLOS_DT          CHAR(8)       NOT NULL, -- 마감일자
	JO_AUTH_NO       CHARACTER VARYING(20)  NULL,     -- 구인인증번호
	PBLANC_NO        CHARACTER VARYING(20)  NULL,     -- 공고번호
	JO_DATA_DIV      CHAR(1)       NOT NULL, -- 구인자료구분
	JO_DATA_KEY      CHARACTER VARYING(20)  NOT NULL, -- 구인자료키
	WORK_REGION      CHARACTER VARYING(200) NOT NULL, -- 근무지역
	WORK_ADDR        CHARACTER VARYING(200) NOT NULL, -- 근무주소
	SIDO_CD          CHAR(2)       NOT NULL, -- 시도코드
	SGG_CD           CHAR(3)       NOT NULL, -- 시군구코드
	EMDONG_CD        CHAR(2)       NOT NULL, -- 읍면동코드
	TOT_OA_CD        CHARACTER VARYING(15)  NULL,     -- 집계구코드
	X                CHARACTER VARYING(20)  NULL,     -- X좌표
	Y                CHARACTER VARYING(20)  NULL,     -- Y좌표
	CREATE_DT        CHAR(8)       NOT NULL  -- 생성일자
);

-- 오늘의구인현황중복제거
ALTER TABLE SRV_DT_JOB_SM_DUPL_REMOVE
	ADD
		CONSTRAINT PK_SRV_DT_JOB_SM_DUPL_REMOVE -- 오늘의구인현황중복제거 기본키
		PRIMARY KEY (
			JO_NO -- 구인번호
		);

-- 오늘의구인현황중복제거
COMMENT ON TABLE SRV_DT_JOB_SM_DUPL_REMOVE IS '오늘의구인현황중복제거';

-- 구인번호
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.JO_NO IS '구인번호';

-- 회사명
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.CORP_NM IS '회사명';

-- 사업자번호
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.BSNM_NO IS '사업자번호';

-- 산업분류
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.INDUST_CLASS IS '산업분류';

-- 기업형태
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.ENTRPRS_TYPE IS '기업형태';

-- 회사규모
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.CORP_SZ IS '회사규모';

-- 근로자수
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.LABRR_CNT IS '근로자수';

-- 회사주소
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.CORP_ADDR IS '회사주소';

-- 자본금
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.CAP IS '자본금';

-- 대표자명
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.MAIN_NM IS '대표자명';

-- 연매출액
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.YEAR_SALES IS '연매출액';

-- 주요사업내용
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.MAIN_BIZ_CONTENT IS '주요사업내용';

-- 회사홈페이지
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.CORP_HPAGE IS '회사홈페이지';

-- 채용명
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.RECRU_NM IS '채용명';

-- 경력
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.CAREER IS '경력';

-- 학력
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.ACDMCR IS '학력';

-- 임금형태
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.WAGE_TYPE IS '임금형태';

-- 급여
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.SALARY IS '급여';

-- 근무형태
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.WORK_TYPE IS '근무형태';

-- 고용형태
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.EMPLYM_TYPE IS '고용형태';

-- 모집직종
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.RCRIT_JSSFC IS '모집직종';

-- 모집인원
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.RCRIT_PSN IS '모집인원';

-- 등록일자
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.REG_DT IS '등록일자';

-- 마감일자
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.CLOS_DT IS '마감일자';

-- 구인인증번호
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.JO_AUTH_NO IS '구인인증번호';

-- 공고번호
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.PBLANC_NO IS '공고번호';

-- 구인자료구분
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.JO_DATA_DIV IS '구인자료구분';

-- 구인자료키
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.JO_DATA_KEY IS '구인자료키';

-- 근무지역
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.WORK_REGION IS '근무지역';

-- 근무주소
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.WORK_ADDR IS '근무주소';

-- 시도코드
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.SIDO_CD IS '시도코드';

-- 시군구코드
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.SGG_CD IS '시군구코드';

-- 읍면동코드
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.EMDONG_CD IS '읍면동코드';

-- 집계구코드
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.TOT_OA_CD IS '집계구코드';

-- X좌표
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.X IS 'X좌표';

-- Y좌표
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.Y IS 'Y좌표';

-- 생성일자
COMMENT ON COLUMN SRV_DT_JOB_SM_DUPL_REMOVE.CREATE_DT IS '생성일자';

-- 오늘의구인현황중복제거 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_SM_DUPL_REMOVE IS '오늘의구인현황중복제거 기본키';

-- 오늘의구인현황중복제거 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_SM_DUPL_REMOVE.PK_SRV_DT_JOB_SM_DUPL_REMOVE IS '오늘의구인현황중복제거 기본키';

-- 일자리통계 외부수집파일자료 원시
CREATE TABLE SRV_DT_JOB_EXTERNAL_FILE_RAW (
	TBL_NM     CHARACTER VARYING(300) NOT NULL, -- 테이블명칭
	ITM_NM     CHARACTER VARYING(200) NOT NULL, -- 아이템명칭
	PRD_DE     CHARACTER VARYING(20)  NOT NULL, -- 수록시점
	AREA_11    CHARACTER VARYING(30)  NULL,     -- 지역11
	AREA_21    CHARACTER VARYING(30)  NULL,     -- 지역21
	AREA_22    CHARACTER VARYING(30)  NULL,     -- 지역22
	AREA_23    CHARACTER VARYING(30)  NULL,     -- 지역23
	AREA_24    CHARACTER VARYING(30)  NULL,     -- 지역24
	AREA_25    CHARACTER VARYING(30)  NULL,     -- 지역25
	AREA_26    CHARACTER VARYING(30)  NULL,     -- 지역26
	AREA_29    CHARACTER VARYING(30)  NULL,     -- 지역29
	AREA_31    CHARACTER VARYING(30)  NULL,     -- 지역31
	AREA_32    CHARACTER VARYING(30)  NULL,     -- 지역32
	AREA_33    CHARACTER VARYING(30)  NULL,     -- 지역33
	AREA_34    CHARACTER VARYING(30)  NULL,     -- 지역34
	AREA_35    CHARACTER VARYING(30)  NULL,     -- 지역35
	AREA_36    CHARACTER VARYING(30)  NULL,     -- 지역36
	AREA_37    CHARACTER VARYING(30)  NULL,     -- 지역37
	AREA_38    CHARACTER VARYING(30)  NULL,     -- 지역38
	AREA_39    CHARACTER VARYING(30)  NULL,     -- 지역39
	AREA_TOTAL CHARACTER VARYING(30)  NULL      -- 지역총합
);

-- 일자리통계 외부수집파일자료 원시
ALTER TABLE SRV_DT_JOB_EXTERNAL_FILE_RAW
	ADD
		CONSTRAINT PK_SRV_DT_JOB_EXTERNAL_FILE_RAW -- 일자리통계 외부수집파일자료 원시 기본키
		PRIMARY KEY (
			TBL_NM, -- 테이블명칭
			ITM_NM, -- 아이템명칭
			PRD_DE  -- 수록시점
		);

-- 일자리통계 외부수집파일자료 원시
COMMENT ON TABLE SRV_DT_JOB_EXTERNAL_FILE_RAW IS '일자리통계 외부수집파일자료 원시';

-- 테이블명칭
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.TBL_NM IS '테이블명칭';

-- 아이템명칭
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.ITM_NM IS '아이템명칭';

-- 수록시점
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.PRD_DE IS '수록시점';

-- 지역11
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_11 IS '지역11';

-- 지역21
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_21 IS '지역21';

-- 지역22
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_22 IS '지역22';

-- 지역23
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_23 IS '지역23';

-- 지역24
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_24 IS '지역24';

-- 지역25
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_25 IS '지역25';

-- 지역26
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_26 IS '지역26';

-- 지역29
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_29 IS '지역29';

-- 지역31
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_31 IS '지역31';

-- 지역32
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_32 IS '지역32';

-- 지역33
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_33 IS '지역33';

-- 지역34
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_34 IS '지역34';

-- 지역35
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_35 IS '지역35';

-- 지역36
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_36 IS '지역36';

-- 지역37
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_37 IS '지역37';

-- 지역38
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_38 IS '지역38';

-- 지역39
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_39 IS '지역39';

-- 지역총합
COMMENT ON COLUMN SRV_DT_JOB_EXTERNAL_FILE_RAW.AREA_TOTAL IS '지역총합';

-- 일자리통계 외부수집파일자료 원시 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_EXTERNAL_FILE_RAW IS '일자리통계 외부수집파일자료 원시 기본키';

-- 일자리통계 외부수집파일자료 원시 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_EXTERNAL_FILE_RAW.PK_SRV_DT_JOB_EXTERNAL_FILE_RAW IS '일자리통계 외부수집파일자료 원시 기본키';

-- 일자리통계자료정보
CREATE TABLE SRV_DT_JOB_STAT_DATA_INFO (
	LINK_ID         CHARACTER VARYING(10)   NOT NULL, -- 연계ID
	STAT_NM         CHARACTER VARYING(200)  NULL,     -- 통계명
	STAT_DEFINITION CHARACTER VARYING(1000) NULL,     -- 통계정의
	STAT_EXP        CHARACTER VARYING(3000) NULL,     -- 통계설명
	COLCT_SOURCE    CHARACTER VARYING(500)  NULL,     -- 수집출처
	UPDT_CYCLE      CHARACTER VARYING(100)  NULL,     -- 갱신주기
	RECENT_UPDT_DE  CHARACTER VARYING(50)   NULL,     -- 최근갱신일
	STAT_PATH       CHARACTER VARYING(300)  NULL,     -- 통계경로
	REFRN_URL       CHARACTER VARYING(500)  NULL,     -- 참조URL
	CREATE_DT       CHAR(8)        NULL      -- 생성일자
);

-- 일자리통계자료정보
ALTER TABLE SRV_DT_JOB_STAT_DATA_INFO
	ADD
		CONSTRAINT PK_SRV_DT_JOB_STAT_DATA_INFO -- 일자리통계자료정보 기본키
		PRIMARY KEY (
			LINK_ID -- 연계ID
		);

-- 일자리통계자료정보
COMMENT ON TABLE SRV_DT_JOB_STAT_DATA_INFO IS '일자리통계자료정보';

-- 연계ID
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.LINK_ID IS '연계ID';

-- 통계명
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.STAT_NM IS '통계명';

-- 통계정의
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.STAT_DEFINITION IS '통계정의';

-- 통계설명
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.STAT_EXP IS '통계설명';

-- 수집출처
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.COLCT_SOURCE IS '수집출처';

-- 갱신주기
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.UPDT_CYCLE IS '갱신주기';

-- 최근갱신일
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.RECENT_UPDT_DE IS '최근갱신일';

-- 통계경로
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.STAT_PATH IS '통계경로';

-- 참조URL
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.REFRN_URL IS '참조URL';

-- 생성일자
COMMENT ON COLUMN SRV_DT_JOB_STAT_DATA_INFO.CREATE_DT IS '생성일자';

-- 일자리통계자료정보 기본키
COMMENT ON INDEX PK_SRV_DT_JOB_STAT_DATA_INFO IS '일자리통계자료정보 기본키';

-- 일자리통계자료정보 기본키
-- COMMENT ON CONSTRAINT SRV_DT_JOB_STAT_DATA_INFO.PK_SRV_DT_JOB_STAT_DATA_INFO IS '일자리통계자료정보 기본키';

-- 일자리통계자료정제
CREATE TABLE SRV_DT_KOSIS_DATA_REFINE (
	ITM_ID        CHARACTER VARYING(50)  NOT NULL, -- 아이템식별자
	ORG_ID        CHARACTER VARYING(5)   NOT NULL, -- 조직식별자
	TBL_ID        CHARACTER VARYING(50)  NOT NULL, -- 테이블식별자
	DT            CHARACTER VARYING(30)  NOT NULL, -- 값데이터
	LINK_ID       CHARACTER VARYING(10)  NOT NULL, -- 연계ID
	PRD_DE        CHARACTER VARYING(20)  NOT NULL, -- 수록시점
	C1            CHARACTER VARYING(50)  NOT NULL, -- 분류1
	CREATE_DT     CHAR(8)       NOT NULL, -- 생성일자
	PRD_SE        CHARACTER VARYING(20)  NULL,     -- 수록주기
	ITM_NM        CHARACTER VARYING(200) NULL,     -- 아이템명칭
	ITM_NM_ENG    CHARACTER VARYING(300) NULL,     -- 아이템명칭영어
	TBL_NM        CHARACTER VARYING(300) NULL,     -- 테이블명칭
	UNIT_NM       CHARACTER VARYING(50)  NULL,     -- 단위명
	UNIT_NM_ENG   CHARACTER VARYING(200) NULL,     -- 단위명영문
	C1_NM         CHARACTER VARYING(200) NULL,     -- 분류1명
	C1_NM_ENG     CHARACTER VARYING(300) NULL,     -- 분류1명영문
	C1_OBJ_NM     CHARACTER VARYING(200) NULL,     -- 분류값1명
	C1_OBJ_NM_ENG CHARACTER VARYING(300) NULL,     -- 분류값1명영문
	C2            CHARACTER VARYING(50)  NULL,     -- 분류2
	C2_NM         CHARACTER VARYING(200) NULL,     -- 분류2명
	C2_NM_ENG     CHARACTER VARYING(300) NULL,     -- 분류2명영문
	C2_OBJ_NM     CHARACTER VARYING(200) NULL,     -- 분류값2명
	C2_OBJ_NM_ENG CHARACTER VARYING(300) NULL,     -- 분류값2명영문
	C3            CHARACTER VARYING(50)  NULL,     -- 분류3
	C3_NM         CHARACTER VARYING(200) NULL,     -- 분류3명
	C3_NM_ENG     CHARACTER VARYING(300) NULL,     -- 분류3명영문
	C3_OBJ_NM     CHARACTER VARYING(200) NULL,     -- 분류값3명
	C3_OBJ_NM_ENG CHARACTER VARYING(300) NULL      -- 분류값3명영문
);

-- 일자리통계자료정제
/*
ALTER TABLE SRV_DT_KOSIS_DATA_REFINE
	ADD
		CONSTRAINT PK_SRV_DT_KOSIS_DATA_REFINE -- 일자리통계자료정제 기본키
		PRIMARY KEY (
			ITM_ID,    -- 아이템식별자
			ORG_ID,    -- 조직식별자
			TBL_ID,    -- 테이블식별자
			DT,        -- 값데이터
			LINK_ID,   -- 연계ID
			PRD_DE,    -- 수록시점
			C1,        -- 분류1
			CREATE_DT  -- 생성일자
		);
*/
-- 일자리통계자료정제
COMMENT ON TABLE SRV_DT_KOSIS_DATA_REFINE IS '일자리통계자료정제';

-- 아이템식별자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.ITM_ID IS '아이템식별자';

-- 조직식별자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.ORG_ID IS '조직식별자';

-- 테이블식별자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.TBL_ID IS '테이블식별자';

-- 값데이터
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.DT IS '값데이터';

-- 연계ID
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.LINK_ID IS '연계ID';

-- 수록시점
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.PRD_DE IS '수록시점';

-- 분류1
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C1 IS '분류1';

-- 생성일자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.CREATE_DT IS '생성일자';

-- 수록주기
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.PRD_SE IS '수록주기';

-- 아이템명칭
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.ITM_NM IS '아이템명칭';

-- 아이템명칭영어
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.ITM_NM_ENG IS '아이템명칭영어';

-- 테이블명칭
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.TBL_NM IS '테이블명칭';

-- 단위명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.UNIT_NM IS '단위명';

-- 단위명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.UNIT_NM_ENG IS '단위명영문';

-- 분류1명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C1_NM IS '분류1명';

-- 분류1명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C1_NM_ENG IS '분류1명영문';

-- 분류값1명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C1_OBJ_NM IS '분류값1명';

-- 분류값1명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C1_OBJ_NM_ENG IS '분류값1명영문';

-- 분류2
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C2 IS '분류2';

-- 분류2명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C2_NM IS '분류2명';

-- 분류2명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C2_NM_ENG IS '분류2명영문';

-- 분류값2명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C2_OBJ_NM IS '분류값2명';

-- 분류값2명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C2_OBJ_NM_ENG IS '분류값2명영문';

-- 분류3
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C3 IS '분류3';

-- 분류3명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C3_NM IS '분류3명';

-- 분류3명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C3_NM_ENG IS '분류3명영문';

-- 분류값3명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C3_OBJ_NM IS '분류값3명';

-- 분류값3명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_REFINE.C3_OBJ_NM_ENG IS '분류값3명영문';

-- 일자리통계자료정제 기본키
-- COMMENT ON INDEX PK_SRV_DT_KOSIS_DATA_REFINE IS '일자리통계자료정제 기본키';

-- 일자리통계자료정제 기본키
-- COMMENT ON CONSTRAINT SRV_DT_KOSIS_DATA_REFINE.PK_SRV_DT_KOSIS_DATA_REFINE IS '일자리통계자료정제 기본키';

-- 일자리통계자료원시
CREATE TABLE SRV_DT_KOSIS_DATA_RAW (
	ITM_ID        CHARACTER VARYING(50)  NOT NULL, -- 아이템식별자
	ORG_ID        CHARACTER VARYING(5)   NOT NULL, -- 조직식별자
	TBL_ID        CHARACTER VARYING(50)  NOT NULL, -- 테이블식별자
	DT            CHARACTER VARYING(30)  NOT NULL, -- 값데이터
	LINK_ID       CHARACTER VARYING(10)  NOT NULL, -- 연계ID
	PRD_DE        CHARACTER VARYING(20)  NOT NULL, -- 수록시점
	C1            CHARACTER VARYING(50)  NOT NULL, -- 분류1
	CREATE_DT     CHAR(8)       NOT NULL, -- 생성일자
	PRD_SE        CHARACTER VARYING(20)  NULL,     -- 수록주기
	ITM_NM        CHARACTER VARYING(200) NULL,     -- 아이템명칭
	ITM_NM_ENG    CHARACTER VARYING(300) NULL,     -- 아이템명칭영어
	TBL_NM        CHARACTER VARYING(300) NULL,     -- 테이블명칭
	UNIT_NM       CHARACTER VARYING(50)  NULL,     -- 단위명
	UNIT_NM_ENG   CHARACTER VARYING(200) NULL,     -- 단위명영문
	C1_NM         CHARACTER VARYING(200) NULL,     -- 분류1명
	C1_NM_ENG     CHARACTER VARYING(300) NULL,     -- 분류1명영문
	C1_OBJ_NM     CHARACTER VARYING(200) NULL,     -- 분류값1명
	C1_OBJ_NM_ENG CHARACTER VARYING(300) NULL,     -- 분류값1명영문
	C2            CHARACTER VARYING(50)  NULL,     -- 분류2
	C2_NM         CHARACTER VARYING(200) NULL,     -- 분류2명
	C2_NM_ENG     CHARACTER VARYING(300) NULL,     -- 분류2명영문
	C2_OBJ_NM     CHARACTER VARYING(200) NULL,     -- 분류값2명
	C2_OBJ_NM_ENG CHARACTER VARYING(300) NULL,     -- 분류값2명영문
	C3            CHARACTER VARYING(50)  NULL,     -- 분류3
	C3_NM         CHARACTER VARYING(200) NULL,     -- 분류3명
	C3_NM_ENG     CHARACTER VARYING(300) NULL,     -- 분류3명영문
	C3_OBJ_NM     CHARACTER VARYING(200) NULL,     -- 분류값3명
	C3_OBJ_NM_ENG CHARACTER VARYING(300) NULL      -- 분류값3명영문
);

-- 일자리통계자료원시
/*
ALTER TABLE SRV_DT_KOSIS_DATA_RAW
	ADD
		CONSTRAINT PK_SRV_DT_KOSIS_DATA_RAW -- 일자리통계자료원시 기본키
		PRIMARY KEY (
			ITM_ID,    -- 아이템식별자
			ORG_ID,    -- 조직식별자
			TBL_ID,    -- 테이블식별자
			DT,        -- 값데이터
			LINK_ID,   -- 연계ID
			PRD_DE,    -- 수록시점
			C1,        -- 분류1
			CREATE_DT  -- 생성일자
		);
*/
-- 일자리통계자료원시
COMMENT ON TABLE SRV_DT_KOSIS_DATA_RAW IS '일자리통계자료원시';

-- 아이템식별자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.ITM_ID IS '아이템식별자';

-- 조직식별자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.ORG_ID IS '조직식별자';

-- 테이블식별자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.TBL_ID IS '테이블식별자';

-- 값데이터
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.DT IS '값데이터';

-- 연계ID
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.LINK_ID IS '연계ID';

-- 수록시점
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.PRD_DE IS '수록시점';

-- 분류1
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C1 IS '분류1';

-- 생성일자
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.CREATE_DT IS '생성일자';

-- 수록주기
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.PRD_SE IS '수록주기';

-- 아이템명칭
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.ITM_NM IS '아이템명칭';

-- 아이템명칭영어
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.ITM_NM_ENG IS '아이템명칭영어';

-- 테이블명칭
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.TBL_NM IS '테이블명칭';

-- 단위명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.UNIT_NM IS '단위명';

-- 단위명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.UNIT_NM_ENG IS '단위명영문';

-- 분류1명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C1_NM IS '분류1명';

-- 분류1명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C1_NM_ENG IS '분류1명영문';

-- 분류값1명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C1_OBJ_NM IS '분류값1명';

-- 분류값1명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C1_OBJ_NM_ENG IS '분류값1명영문';

-- 분류2
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C2 IS '분류2';

-- 분류2명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C2_NM IS '분류2명';

-- 분류2명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C2_NM_ENG IS '분류2명영문';

-- 분류값2명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C2_OBJ_NM IS '분류값2명';

-- 분류값2명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C2_OBJ_NM_ENG IS '분류값2명영문';

-- 분류3
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C3 IS '분류3';

-- 분류3명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C3_NM IS '분류3명';

-- 분류3명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C3_NM_ENG IS '분류3명영문';

-- 분류값3명
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C3_OBJ_NM IS '분류값3명';

-- 분류값3명영문
COMMENT ON COLUMN SRV_DT_KOSIS_DATA_RAW.C3_OBJ_NM_ENG IS '분류값3명영문';

-- 일자리통계자료원시 기본키
-- COMMENT ON INDEX PK_SRV_DT_KOSIS_DATA_RAW IS '일자리통계자료원시 기본키';

-- 일자리통계자료원시 기본키
-- COMMENT ON CONSTRAINT SRV_DT_KOSIS_DATA_RAW.PK_SRV_DT_KOSIS_DATA_RAW IS '일자리통계자료원시 기본키';

-- 구인자료 수집 정보 분석
CREATE TABLE srv_dt_job_data_profile
(
    reg_dt character(8),		-- 수집일자
    w_gather_cnt integer,		-- 워크넷 수집건수
    w_null_bsnm_no integer,		-- 워크넷 사업자번호 null 건수
    w_null_corp_sz integer,		-- 워크넷 회사규모 null 건수
    w_null_work_intspt integer,	-- 워크넷 근무지주소 null 건수
    w_null_biz_nm integer,		-- 워크넷 산업분류 null 건수
    w_null_rcrit_jssfc integer,	-- 워크넷 직종 null 건수
    w_null_rcrit_psn integer,	-- 워크넷 모집인원 null 건수
    w_null_emplym_type integer,	-- 워크넷 고용형태 null 건수
    w_null_career integer,		-- 워크넷 경력 null 건수
    w_null_acdmcr integer,		-- 워크넷 학력 null 건수
    w_null_salary integer,		-- 워크넷 급여 null 건수
    w_null_wage_cnd integer,	-- 워크넷 급여형태 null 건수
    i_gather_cnt integer,       -- 인크루트 수집건수
    i_null_bsnm_no integer,     -- 인크루트 사업자번호 null 건수
    i_null_corp_sz integer,     -- 인크루트 회사규모 null 건수
    i_null_work_intspt integer, -- 인크루트 근무지주소 null 건수
    i_null_biz_nm integer,      -- 인크루트 산업분류 null 건수
    i_null_rcrit_jssfc integer, -- 인크루트 직종 null 건수
    i_null_rcrit_psn integer,   -- 인크루트 모집인원 null 건수
    i_null_emplym_type integer, -- 인크루트 고용형태 null 건수
    i_null_career integer,      -- 인크루트 경력 null 건수
    i_null_acdmcr integer,      -- 인크루트 학력 null 건수
    i_null_salary integer,      -- 인크루트 급여 null 건수
    i_null_wage_cnd integer,    -- 인크루트 급여형태 null 건수
    duple_cnt integer,          -- 중복 건수
    total_cnt integer,          -- 총건수
    create_dt character(8),     -- 생성일자
    total_job_refine_cnt integer,   -- 정제건수
    geo_coding_err_cnt integer      -- 지오코딩 오류 건수
) ;


-- 구인자료 집계 정보 분석
CREATE TABLE srv_dt_job_data_sm_all_profile
(
    reg_dt character(8),					-- 집계일자
    b_class_cd character varying(6),		-- 분류코드
    b_class_cd_nm character varying(100),	-- 분류명
    s_class_cd character varying(10),		-- 코드
    s_class_cd_nm character varying(100),	-- 코드명
    jo_cnt integer,							-- 구인건수
    rcrit_psn_cnt integer,					-- 모집인원수
    create_dt	CHAR(8)						-- 생성일자
) ; 

-- 사업체 정보 : 사업자번호|산업분류
-- Table: saupche_tb_2017_refine
-- DROP TABLE saupche_tb_2017_refine;
CREATE TABLE saupche_tb_2017_refine
(
    crn character varying(10),
    indust_class character varying(6)
);

-- Index: IX_saupche_tb_2017_refine
-- DROP INDEX jobsvc."IX_saupche_tb_2017_refine";
CREATE INDEX "IX_saupche_tb_2017_refine"
    ON saupche_tb_2017_refine USING btree
    (crn varchar_ops)
;